### ISSUE TITLE
passwords longer than 19 chars are broken

### ISSUE THREAD

**Issue by landroni** [richbeales/passwordmaker-python#1]
Generate a password using 
URL: passwordmaker.org
MPW: asdf
Length: 30

and defaults elsewhere. You should get: 
FRRHm)k+UyQiY~%Dj;hH(qNT;{OFZ2

Repeat the procedure in [1] (or using the CLI edition) and you should get: 
FRRHm)k+UyQiY~%Dj;h*FV[{:5X@EN

Up to the 19th char inclusive the passwords seem identical, but then they diverge. I assume that the implementation is broken in the Python version. 

[1] http://passwordmaker.org/passwordmaker.html

**Comment by csarn** [comment]
found the bug and fixed it. see my pull request :)

**Comment by richbeales** [comment]
Cheers!
